//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Carrito.java
//  @ Date : 29/07/2021
//  @ Author : 
//
//

package clase27;

import java.util.ArrayList;

public class Carrito {
	private ArrayList<Producto> productosComprados;

	public Carrito() {
		productosComprados = new ArrayList<>();
	}
	public void agregarProducto(Producto producto) {
		productosComprados.add(producto);
	}
	
	public double importeTotal() {
		double total = 0;
		for (Producto prod:productosComprados) {
			total += prod.precioVenta();
		}
		return total;
	}
	
	public void Carrito() {
		productosComprados = new ArrayList<>();
	}
}
