//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 29/07/2021
//  @ Author : 
//
//

package clase27;


public class Cliente {
	private String nombre;
	private String apellido;
	private String email;
	private Carrito carrito;

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Cliente(String nom, String ape, String email) {
		nombre = nom;
		apellido = ape;
		this.email = email;
		carrito = new Carrito();
	}
	
	public void agregarProducto(Producto producto) {
		carrito.agregarProducto(producto);
	}
	
	public double pagar() {
		System.out.println("Pagando el total de "+carrito.importeTotal());
		return carrito.importeTotal();
	}
}
