//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Local.java
//  @ Date : 29/07/2021
//  @ Author : 
//
//

package clase27;


import java.util.ArrayList;

public class Local {
	private String nombre;
	private String telefono;
	private String email;
	private ArrayList<Producto> productos;
	private ArrayList<Cliente> clientes;

	public void local(String nom, String tel, String email) {
		nombre = nom;
		telefono = tel;
		this.email = email;
		productos = new ArrayList<>();
		clientes = new ArrayList<>();
	}
	
	public void agregarProducto(int cod, String nom, double costo) {
		productos.add(new Producto(cod,nom,costo));
	}
	
	public void agregarCliente(String nom, String ape, String email) {
		clientes.add(new Cliente(nom, ape, email));
	}
	
	public double totalCompra(String email) {
		for (Cliente c:clientes)
			if (c.getEmail() == email) {
				return c.pagar();
			}
		return 0;
	}
	
	public void cambiarCosto(int cod, double nuevoCosto) {
		for (Producto prod:productos) {
			if (prod.getCodigo()==cod){
				prod.cambiar(nuevoCosto);
			}
		}
	}
}
