//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Producto.java
//  @ Date : 29/07/2021
//  @ Author : 
//
//

package clase27;


public class Producto {
	private int codigo;
	private String nombre;
	private double costo;

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public double precioVenta() {
		return costo*1.3;
	}
	
	public void cambiar(double costo) {
		this.costo = costo;
	}
	
	public Producto(int cod, String nom, double costo) {
		codigo = cod;
		nombre = nom;
		this.costo = costo;
	}
}
